version: "3.1"

services:
  db-service:
    container_name: db
    build:
      context: ./db
    restart: always
    env_file:
      - db/.env
    networks:
      - nikochopikashvili

  gateway:
    container_name: gateway
    build:
      context: ./gateway/src
    restart: always
    ports:
      - 80:8080
    networks:
      - nikochopikashvili

  service-auth:
    container_name: service-auth
    build:
      context: ../auth
    restart: always
    env_file:
      - service/auth/.env
    networks:
      - nikochopikashvili

  service-posts:
    container_name: service-posts
    build:
      context: ../posts
    restart: always
    env_file:
      - service/posts/.env
    networks:
      - nikochopikashvili

networks:
  nikochopikashvili:
    external: true
